
version: '3.8'

services:
  client:
    build:
      context: ../client
      dockerfile: ../dev-config/DockerFile.client
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes:
      - ../client:/usr/app
    environment: 
      API_URL: ${API_URL}
      API_SECRET: ${API_SECRET}
      restart: unless-stopped
    networks:
      - link-blink

  server:
    build:
      context: ../server
      dockerfile: ../dev-config/DockerFile.server
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ../server:/usr/app
    environment: 
      API_URL: ${API_URL}
      EXPIRE_JWT: ${EXPIRE_JWT}
      API_PORT: ${API_PORT}
      DB_PORT: ${DB_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      API_SECRET: ${API_SECRET}
      restart: unless-stopped
    networks:
      - link-blink

  db:
    image: postgres:15
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db:/data/db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

      restart: unless-stopped
    networks:
      - link-blink

networks:
  link-blink:
volumes:
  db:

